name: Bump latest Kubernetes dependecies

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

  workflow_dispatch:

jobs:
  bump-to-latest-pre-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Bump latest k8s.io dependencies
        run: bash ./hack/bump-k8s-dep.sh
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check for changes
        id: changes
        run: |
          echo "::set-output name=changes::$(git diff)"

      - name: Create PR
        if: steps.changes.outputs.changes
        run: |
          HEAD_BRANCH="auto-bump-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$HEAD_BRANCH"
          git add go.mod go.sum
          git commit -sm "Bump the Kubernetes group updates"
          git push origin "$HEAD_BRANCH"
          gh pr create --base master --title ":seedling: Bump the Kubernetes group updates" --label "ok-to-test" --body "This is an automated pull request generated to bump the latest k8s dependencies."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
